stages:
  - build
  - test

build-code-job:
  stage: build
  script:
    - echo "Check the gradle version, then build some spring project files:"
    - ./gradlew -v
    - rake

test-code-job1:
  stage: test
  script:
    - echo "If the files are built successfully, test some files with one command:"
    - rake test1

test-code-job2:
  stage: test
  script:
    - echo "If the files are built successfully, test other files with a different command:"
    - rake test2